#!/bin/dash
#▶ Simple file system navigator/viewer. See License file for copyright and license info.
#▶ Run: source nav
#▶ Controls: hjkl to move, q to quit
#▶ Install: Add an alias for this to your ~/.bash_aliases file: f='source PATH_TO_THIS_SCRIPT'

# Sort the filenames and group them using html-like tags:
update_names() {
NAMES="\
<@public dirs@>
$(find -L . -maxdepth 1 -type d | sed 's/^\.\///' | grep -v '^\.' | sort)
<@end@>
<@private dirs@>
$(find -L . -maxdepth 1 -type d | sed 's/^\.\///' | grep '^\.' | grep -v '^.$' | sort)
<@end@>
<@public files@>
$(find -L . -maxdepth 1 -type f | sed 's/^\.\///' | grep -v '^\.' | sort)
<@end@>
<@private files@>
$(find -L . -maxdepth 1 -type f | sed 's/^\.\///' | grep '^\.' | sort)
<@end@>
"
FORMATTED_NAMES="$(
printf "$NAMES" | # Set color-coding for each tagged group of names:
    sed '
        /^\s*$/d;
        /<@public dirs@>/,/<@end@>/s/^/\\033[93m/
        /<@private dirs@>/,/<@end@>/s/^/\\033[91m/
        /<@public files@>/,/<@end@>/s/^/\\033[37m/
        /<@private files@>/,/<@end@>/s/^/\\033[32m/
        /<@.*@>/d
        s/$/\\033[0m/
    '
)"
SORTED_NAMES="$(printf "$NAMES" | sed '/^\s*$/d; /^<@.*@>$/d')"
}

REFRESH=1
CURSOR_POS=2
SCROLL_HEIGHT=1
update_names
# Hide user input:
stty -echo
# Navigation loop:
while (true) do
    # Get the terminal dimensions: (so we don't over-fill the screen)
    W="$(tput cols)"
    H="$(tput lines)"
    NUM_FILES="$(echo "$FORMATTED_NAMES" | wc -l)"
    NUM_FILES="$((NUM_FILES+1))"
    # Keep the cursor in bounds:
    (( CURSOR_POS < 2 )) && CURSOR_POS=2 && SCROLL_HEIGHT=$((SCROLL_HEIGHT-1)) && REFRESH=1 # Top.
    (( CURSOR_POS > H )) && SCROLL_HEIGHT=$((SCROLL_HEIGHT+((CURSOR_POS-H)))) && CURSOR_POS=$H && REFRESH=1 # Bottom.
    (( CURSOR_POS > ((NUM_FILES)) )) && CURSOR_POS="$((NUM_FILES))" # Last file.
    (( SCROLL_HEIGHT > ((NUM_FILES-H)) )) && SCROLL_HEIGHT="$((NUM_FILES-H))"
    (( SCROLL_HEIGHT < 1 )) && SCROLL_HEIGHT=1
    # Draw the diplay:
    [ "$REFRESH" = "1" ] &&
        clear &&
        # Print the current directory: (formatted to be yellow)
        printf "\033[93m$PWD\033[0m\n" &&
        # Print the file names: (with leading space)
        printf "$(sed 's/^/ /' <<< "$FORMATTED_NAMES" | sed -n ' '"$SCROLL_HEIGHT"','"$((H+SCROLL_HEIGHT-2))"'p')"
    # Move the cursor:
    printf "\033[$CURSOR_POS;0H"
    # Only set to 1 when the display needs to change:
    REFRESH=0
    # Get user input: (don't wait for enter to be pressed)
    read -ern 1 INPUT
    # Quit:
    [ "$INPUT" = "q" ] && break
    # Goto ..:
    [ "$INPUT" = "h" ] &&
        PREV_FNAME="${PWD##*/}" && # Get the name of the current dir.
        cd ".." &&
        REFRESH=1 &&
        update_names &&
        CURSOR_POS="$(grep -n "^$PREV_FNAME\$" <<< "$SORTED_NAMES" | cut -d ':' -f 1)" &&
        CURSOR_POS="$((CURSOR_POS+1))" # Set cursor on dir we just came from.
    # Goto dir:
    [ "$INPUT" = "l" ] && cd "$(echo "$SORTED_NAMES" | tr '\n' '\t' | cut -f "$((CURSOR_POS+SCROLL_HEIGHT-2))")" && REFRESH=1 && update_names
    # Up:
    [ "$INPUT" = "k" ] && CURSOR_POS=$((CURSOR_POS-1))
    # Down:
    [ "$INPUT" = "j" ] && CURSOR_POS=$((CURSOR_POS+1))
done

# Clear formatting, move cursor to bottom of the terminal.
N="$(echo "$SORTED_NAMES" | wc -l)"
N=$((N+1))
printf "\033[$N;0H \033[0m \033[0J \033[$N;0H"
# Show user input:
stty echo
